### ISSUE TITLE
Japanese not appear listed

### ISSUE THREAD

**Issue by Ciana1220** [kamoo1/anki-word-freq#1]
Hello, I installed the CJK version, but these languages ​​do not appear listed for selection

![CKJSem título](https://github.com/kamoo1/anki-word-freq/assets/122986073/e36009f8-55af-403b-8241-088f1752980c)

**Comment by kamoo1** [comment]
Hi, thanks for the report, that was my oversight, it should be fixed now in 0.1.3

https://github.com/kamoo1/anki-word-freq/releases/download/v0.1.3/ankiwordfreq_0.1.3_cjk.ankiaddon

**Comment by Ciana1220** [comment]
It's working fine now, thank you very much
