### ISSUE TITLE
Add a frequency coefficient inversion setting.

### ISSUE THREAD

**Issue by Zaxvatov** [kamoo1/anki-word-freq#2]
The standard sorting in ascending order (from 1 to 9) implies that a record with index 1 is "more important" than a record with index 9. However, the frequency coefficient has the opposite interpretation: the higher it is, the more important the word is, and it should be learned first. This creates logikal conflicts.

For example, if we take two records (with frequency coefficients of 5.66 and 6.25, respectively) that have 6 card types each, sorting them in ascending order would result in the following list. 
Note that the list has the correct sorting by card types (from 1 to 6), but the wrong sorting by frequency coefficient, as the more frequent words are at the bottom.
![image](https://github.com/user-attachments/assets/932083c8-8603-414d-ba28-723410cb45ef)

If we switch to descending order, the frequency coefficient sorting will be correct, but the card type sorting will be reversed (from 6 to 1).
![image](https://github.com/user-attachments/assets/5a1b8da1-b4bb-4a87-97fe-249071a549c8)

Therefore, for proper display, the frequency coefficient needs to be inverted. As a result, sorting in ascending order will look as follows.
![image](https://github.com/user-attachments/assets/622c2e94-f1a9-4992-b53e-a9ead2e49442)

With this sorting, the "Bury new siblings" deck setting will work correctly. 
![image](https://github.com/user-attachments/assets/4f6ad3fe-0768-4a0a-acd1-f41a0d6e9c7a)
Currently, when sorted in ascending order, ANKI offers the card with type 1, but it happens to be the least important card with the lowest frequency coefficient. If we switch to descending order, ANKI will offer the card with the highest frequency coefficient, but it will start with card type 6, which is not correct.

I propose the following implementation: If the maximum frequency coefficient is 10, then when the "Inversion" setting in config of the add-on is activated, the coefficients will be assigned based on the formula 10-X, where "X" is the current frequency coefficient of the note.

**Comment by kamoo1** [comment]
Thank you for your contribution, I find it reasonable and very detailed. I will start working on this these days. 

The upper limit should be less than 10, but I will check that to make sure.

(I wasn't checking my GitHub recently, hope you didn't felt frustrated...)
